CREATE TABLE USUARIOS (
	ID INTEGER NOT NULL,
	USUARIO VARCHAR(100),
	CLAVE VARCHAR(100),
	NOMBRES VARCHAR(100) NOT NULL,
	CONSTRAINT USUARIOS_PK PRIMARY KEY (ID)
);

INSERT INTO USUARIOS (ID, USUARIO, CLAVE, NOMBRES)
VALUES (1, 'usuario1',	'123', 'Usuario 1');

INSERT INTO USUARIOS (ID, USUARIO, CLAVE, NOMBRES)
VALUES (2, 'usuario2',	'123', 'Usuario 2');

INSERT INTO USUARIOS (ID, USUARIO, CLAVE, NOMBRES)
VALUES (3, 'usuario3',	'123', 'Usuario 3');

CREATE TABLE USUARIOS_DISPOSITIVOS (
	TOKEN_DISPOSITIVO VARCHAR(255),
	USUARIO_ID INTEGER
);

INSERT INTO USUARIOS_DISPOSITIVOS (TOKEN_DISPOSITIVO,USUARIO_ID) VALUES
	 ('cqPP0V-hpllQCsOLBeMr_d:APA91bFPhONkvUqLiBaMY_4fDA3evK0VdQWBn5lN04wGw4DmWPvlPlXuNIJZKXP_utDSZOlse133Dhc1QAwPaygAKIMjEvePjcdcy9K1x2RWYf2XpNbMr_TO8grAaQLkK5pq2femQkKA',1),
	 ('cqPP0V-hpllQCsOLBeMr_d:APA91bFJq3EtGvxu7Ov9GIqraNNHoDUlVLLWNf3QbQknfSTkfAKlSoyvnziHI8VqfGQcCErXryRHgxN4AP-KsHN_AeaIQuyJ2yu4dJWYIRQaJeivvCkPrMMgRhY0IWult35QaZEEdhN6',1),
	 ('cqPP0V-hpllQCsOLBeMr_d:APA91bF40ZGYIXmAqKZTHCGGOaoJ6AM9OJMAllaj3IzprtBco5dPtkfMhPIohzLPNZOoNplkM0UBPiGJH6twNKYibNIa3OYiZODCkLxvLzdsJ0UE1KYgLx5ibpypnBz25fOKTf51I_Nz',1),
	 ('e-gIABnJY5qi7KHjkiQhxj:APA91bF9BNvq3rP4NTnZyguVfhwq3cfeaZOkRbVmdCbVLRwl7SSgpbdOIJiaeV-_qWoSGACUSS9ue7oVNO5lsRGxZq3Jrlah4Ic4e2exRHYOcD_rt9uo8hFXvf227WMg_LBFBFZrMLnk',1),
	 ('e-gIABnJY5qi7KHjkiQhxj:APA91bHuFrsutHDi5lVdZcprNPx3BghFlKDZ_VfHAOzHJ7P9zKxgLzBx_O7jFlY8pIzBieM2Gbj9wlybUZyCBL8MRoTSO5_IG7gKcXMoU0jmieBLLkNWvVi0vWD0DMhws8lwAz2XofdW',1),
	 ('e-gIABnJY5qi7KHjkiQhxj:APA91bFjjyUC0ZMwvvIs16NlTD-d4ZiN1iQlCOyp_T3X2mkvA8k5eB8UKiB84Ejl0fgkUkCGS7edFzDsu_QnBWgSbQmUfrwpD1FQuipH5dH7YWYLWszP5qlfOvrDdZazjccE3m_b_BHp',1),
	 ('e-gIABnJY5qi7KHjkiQhxj:APA91bEghhZ5Tsw1pNFUDzE4RJwnLr5k0Xp-BNig8B28Ex2nfh7k_T_4noyrkOfOn1NKi-upiEkWKaMy9I2Fda6wa4WNAyVPFtNiaGxFYeB8wSEGK1F-gfsl7ETW-9USgqlPRJut0CRw',1);
