CREATE TABLE USUARIOS (
	ID INTEGER NOT NULL,
	USUARIO VARCHAR(100),
	CLAVE VARCHAR(100),
	NOMBRES VARCHAR(100) NOT NULL,
	CONSTRAINT USUARIOS_PK PRIMARY KEY (ID)
);

INSERT INTO USUARIOS (ID, USUARIO, CLAVE, NOMBRES)
VALUES (1, 'usuario1',	'123', 'Usuario 1');

INSERT INTO USUARIOS (ID, USUARIO, CLAVE, NOMBRES)
VALUES (2, 'usuario2',	'123', 'Usuario 2');

INSERT INTO USUARIOS (ID, USUARIO, CLAVE, NOMBRES)
VALUES (3, 'usuario3',	'123', 'Usuario 3');